version: "3.8"
services:
  bruce:
    image: ghcr.io/uoncompsoc/bruce:latest
    container_name: bruce
    build: .
    environment:
      PUID: 1000
      PGID: 1000
    env_file:
      - .env
    volumes:
      - ./data:/data
